Templating additional values
wiremock/helm-charts pull request #32
Opened 2024-02-25 14:43 UTC by rliskunov

I'm using additional variables inside `values.yaml`.

For example, `domain: {{ .Chart.Name }}.{{ .Values.ingress.stage }}` and I add it to `ingress.hosts[0].{{ domain }}`.
 
However, the values are not substituted after templating. This is due to the lack of a call to the `tpl` function. This Pull Request is designed to solve this problem

Additionally, I put `.gitignore` to exclude unused files from the repository.

## References

- Personal problem in my pet project

## Submitter checklist

- [x] Recommended: Join [WireMock Slack](https://slack.wiremock.org/) to get any help in `#help-contributing` or a project-specific channel like `#wiremock-java`
- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)
- [x] Test coverage that demonstrates that the change works as expected
- [x] For new features, there's necessary documentation in this pull request or in a subsequent PR to [wiremock.org](https://github.com/wiremock/wiremock.org)

2024-03-26 23:25 UTC, gitkent requested changes
@rliskunov thanks for your PR. A few things here:
- please remove the `.gitignore` file as it is specific to your local setup but not `helm` related
- please keep correct and indentation, ideally we want to keep the original indentation
- for your templating issue, please elaborate more about what you are trying to achieve? As most of the YAML templates were generated from `helm create` command. It would be cleaner to keep the original unless there is a real necessity.

2025-01-06 13:36 UTC, matera-dgr approved these changes

2025-03-19 15:58 UTC, oranerez commented
@rliskunov @gitkent - can we prioritize this fix for the next version by merge it please?

2025-03-19 16:34 UTC, rliskunov commented
@matera-dgr @gitkent sorry it took so long. I made the final edits. Take a look at this, please.

2025-03-24 09:59 UTC, oranerez approved these changes

2025-03-24 11:01 UTC, oranerez commented
@gitkent May you please review and approve the pull request so it will be able to be merged for the next release?
Thank you.

2025-03-27 11:02 UTC, gitkent commented
> @matera-dgr @gitkent sorry it took so long. I made the final edits. Take a look at this, please.

@rliskunov please take a look into the CI build is failing. Thanks

2025-03-27 11:08 UTC, rliskunov commented
@gitkent bumped a version. I need your approve

2025-03-27 11:16 UTC, gitkent approved these changes

2025-03-27 11:17 UTC, merged